plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.dublispeed'
    compileSdk 36

    defaultConfig {
        applicationId "com.example.dublispeed"
        minSdk 33
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.activity:activity:1.9.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
}